version: "3.7"
services:
    app_4estacoes:
        build:
            args:
                user: luanramos
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        ports:
            - 9010:9000
        environment:
            PHP_IDE_CONFIG: "serverName=ace3"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./:/var/www
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        depends_on:
            - redis_atual
        networks:
            - atual_network

    npm:
        image: node:current-alpine
        volumes:
            - ./:/var/www/
        entrypoint: ["npm"]
        working_dir: /var/www/
        networks:
            - atual_network

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8040:80
            - 445:443
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - atual_network

    db_4estacoes:
        image: mysql
#        platform: linux/arm64/v8
        restart: unless-stopped
        expose:
            - 3308
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - /var/lib/mysql
        ports:
            - 3380:3308
            - 3390:3308
        networks:
            - atual_network

    db_atual_test:
        image: mysql
#        platform: linux/arm64/v8
        restart: unless-stopped
        expose:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - /var/lib/mysql
        ports:
            - 3370:3306
        networks:
            - atual_network

    redis_atual:
        image: redis:latest
        networks:
            - atual_network

networks:
    atual_network:
        driver: bridge
